module AbsholOgram where

-- Haskell module generated by the BNF converter

newtype Ident = Ident String deriving (Eq,Ord,Show)
data Process =
   Selection [GuardedProcess]
 | Composition [Process]
 | Dereference Site
  deriving (Eq,Ord,Show)

data GuardedProcess =
   Input Site Abstraction
 | Output Site Concretion
  deriving (Eq,Ord,Show)

data Abstraction =
   AgentIn [Pattern] Process
  deriving (Eq,Ord,Show)

data Concretion =
   AgentOut [Pattern] [Process] Process
  deriving (Eq,Ord,Show)

data Pattern =
   Value Code
 | QueryPattern Query
  deriving (Eq,Ord,Show)

data Query =
   SumQuery Sum
 | ParQuery [Pattern]
 | DropQuery Pattern
 | RecQuery Ident Pattern
  deriving (Eq,Ord,Show)

data Sum =
   Variable Variable
 | Summand [GuardedPattern]
  deriving (Eq,Ord,Show)

data GuardedPattern =
   AbsPattern TuplePattern Query
 | DataPattern TuplePattern TuplePattern Query
 | DerefPattern Variable Query
  deriving (Eq,Ord,Show)

data TuplePattern =
   TupleVariable Variable
 | TupleList [NestedTuplePattern]
 | TupleCons Pattern TuplePattern
  deriving (Eq,Ord,Show)

data NestedTuplePattern =
   Base Pattern
 | Nesting TuplePattern
  deriving (Eq,Ord,Show)

data Site =
   CodeSite Code
 | VariableSite Variable
  deriving (Eq,Ord,Show)

data Code =
   Quotation Process
  deriving (Eq,Ord,Show)

data Variable =
   Identifier Ident
 | Wildcard Underscore
  deriving (Eq,Ord,Show)

data Value =
   Codification Code
 | Ground GroundLiteral
  deriving (Eq,Ord,Show)

data GroundLiteral =
   Boolean BooleanLiteral
 | Char Char
 | Integer Integer
 | Double Double
 | String String
  deriving (Eq,Ord,Show)

data BooleanLiteral =
   BooleanTrue
 | BooleanFalse
  deriving (Eq,Ord,Show)

data Case =
   CaseIt
  deriving (Eq,Ord,Show)

data Rec =
   RecIt
  deriving (Eq,Ord,Show)

data Models =
   ModelIt
  deriving (Eq,Ord,Show)

data Par =
   ParIt
  deriving (Eq,Ord,Show)

data Zero =
   ZeroIt
  deriving (Eq,Ord,Show)

data LParen =
   LParenIt
  deriving (Eq,Ord,Show)

data RParen =
   RParenIt
  deriving (Eq,Ord,Show)

data LMSet =
   LMSetIt
  deriving (Eq,Ord,Show)

data RMSet =
   RMSetIt
  deriving (Eq,Ord,Show)

data LAngle =
   LAngleIt
  deriving (Eq,Ord,Show)

data RAngle =
   RAngleIt
  deriving (Eq,Ord,Show)

data LBrack =
   LBrackIt
  deriving (Eq,Ord,Show)

data RBrack =
   RBrackIt
  deriving (Eq,Ord,Show)

data LCurly =
   LCurlyIt
  deriving (Eq,Ord,Show)

data RCurly =
   RCurlyIt
  deriving (Eq,Ord,Show)

data Quote =
   QuoteIt
  deriving (Eq,Ord,Show)

data Bang =
   BangIt
  deriving (Eq,Ord,Show)

data Whimper =
   WhimperIt
  deriving (Eq,Ord,Show)

data Ampersand =
   AmpersandIt
  deriving (Eq,Ord,Show)

data Tilde =
   TildeIt
  deriving (Eq,Ord,Show)

data At =
   AtIt
  deriving (Eq,Ord,Show)

data Star =
   StarIt
  deriving (Eq,Ord,Show)

data Dot =
   DotIt
  deriving (Eq,Ord,Show)

data Underscore =
   UnderscoreIt
  deriving (Eq,Ord,Show)

data Assign =
   AssignIt
  deriving (Eq,Ord,Show)

data Cons =
   ConsIt
  deriving (Eq,Ord,Show)

data LQuote =
   LQuoteIt
  deriving (Eq,Ord,Show)

data RQuote =
   RQuoteIt
  deriving (Eq,Ord,Show)

